apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iocheck.fullname" . }}-app
  labels:
    {{- include "iocheck.labels" . | nindent 4 }}
type: Opaque
stringData:
  IOCHECK_DATABASE_URL: postgres://{{ .Values.postgres.auth.user }}:{{ .Values.postgres.auth.password }}@{{ include "iocheck.postgresName" . }}:5432/{{ .Values.postgres.auth.database }}
  REDIS_URL: redis://{{ include "iocheck.redisName" . }}:6379
